### ISSUE TITLE
[Issue] Not being redirected back to app on iOS after following the complete tutorial (works fine on Android)

### ISSUE THREAD

**Issue by Thisgio** [alexziskind1/nativescript-oauth2#167]
### Which platform(s) does your issue occur on?
- iOS
- 14.4.2 
- iPhone 8

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- Cross-platform modules: 7.3.0
- Runtime(s): 8.0.0
- Plugin(s): 
```
"dependencies": {
    "@nativescript/core": "^7.3.0",
    "@nativescript/theme": "^2.3.3",
    "@vue/devtools": "^5.3.3",
    "css-loader": "^5.2.4",
    "nativescript-oauth2": "^3.0.5",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-vue": "^2.8.1",
    "nativescript-vue-devtools": "^1.4.0",
    "odata-query": "^6.7.0",
    "vue-class-component": "^7.2.6",
    "vue-property-decorator": "^9.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "^7.0.0",
    "@nativescript/webpack": "^3.0.4",
    "@triniwiz/nativescript-socketio": "^4.0.1",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "@types/node": "^14.6.2",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "babel-loader": "^8.1.0",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "sass": "^1.26.10",
    "typescript": "^3.9.7",
    "vue": "^2.6.12",
    "vue-loader": "^15.9.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
When I try to login to Azure AD on iOS, it gets stuck and doesn't send me back to the app. When I click login in the microsoft environment I get a quick view of the url scheme, which I put in the info.plist and then it just keeps loading and doesn't turn back to the app.

On Android it works perfectly fine. I followed the tutorial (with the info.plist), and edited the CFBundleUrlName and the string value to my own msal url scheme.

### Is there any code involved? 
 There is no code other than the code in the demo.

Any suggestions?

PS: Only difference between AndroidManifest.Xml and info.plist is that in the AndroidManifest you specify the android:path with "/auth". I don't see that anywhere in the info.plist.

**Comment by Thisgio** [comment]
@alexziskind1 is this a known problem?

**Comment by JCpoz123** [comment]
We are experiencing the same issue in our app after updating to 3.0.3

**Comment by Thisgio** [comment]
There is a temporary fix described here: https://github.com/alexziskind1/nativescript-oauth2/issues/156.

Goodluck :).

**Comment by Thisgio** [comment]
This problem has been fixed with the new https://github.com/alexziskind1/nativescript-oauth2/pull/166.

**Comment by noturtype** [comment]
Still seeing this issue on 3.0.7. Works fine in Android but hangs in iOS after 2FA request is approved.
